/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.upsmart.server.trans.transinterface;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-05-16")
public class BinaryData implements org.apache.thrift.TBase<BinaryData, BinaryData._Fields>, java.io.Serializable, Cloneable, Comparable<BinaryData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BinaryData");

  private static final org.apache.thrift.protocol.TField LENGTH_FIELD_DESC = new org.apache.thrift.protocol.TField("length", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField CHECKALGORITHM_FIELD_DESC = new org.apache.thrift.protocol.TField("checkalgorithm", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField CHECKCODES_FIELD_DESC = new org.apache.thrift.protocol.TField("checkcodes", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("data", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new BinaryDataStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new BinaryDataTupleSchemeFactory();

  public long length; // optional
  public java.lang.String checkalgorithm; // optional
  public java.nio.ByteBuffer checkcodes; // optional
  public java.nio.ByteBuffer data; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LENGTH((short)1, "length"),
    CHECKALGORITHM((short)2, "checkalgorithm"),
    CHECKCODES((short)3, "checkcodes"),
    DATA((short)4, "data");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LENGTH
          return LENGTH;
        case 2: // CHECKALGORITHM
          return CHECKALGORITHM;
        case 3: // CHECKCODES
          return CHECKCODES;
        case 4: // DATA
          return DATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __LENGTH_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.LENGTH,_Fields.CHECKALGORITHM,_Fields.CHECKCODES,_Fields.DATA};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LENGTH, new org.apache.thrift.meta_data.FieldMetaData("length", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.CHECKALGORITHM, new org.apache.thrift.meta_data.FieldMetaData("checkalgorithm", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CHECKCODES, new org.apache.thrift.meta_data.FieldMetaData("checkcodes", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.DATA, new org.apache.thrift.meta_data.FieldMetaData("data", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BinaryData.class, metaDataMap);
  }

  public BinaryData() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BinaryData(BinaryData other) {
    __isset_bitfield = other.__isset_bitfield;
    this.length = other.length;
    if (other.isSetCheckalgorithm()) {
      this.checkalgorithm = other.checkalgorithm;
    }
    if (other.isSetCheckcodes()) {
      this.checkcodes = org.apache.thrift.TBaseHelper.copyBinary(other.checkcodes);
    }
    if (other.isSetData()) {
      this.data = org.apache.thrift.TBaseHelper.copyBinary(other.data);
    }
  }

  public BinaryData deepCopy() {
    return new BinaryData(this);
  }

  @Override
  public void clear() {
    setLengthIsSet(false);
    this.length = 0;
    this.checkalgorithm = null;
    this.checkcodes = null;
    this.data = null;
  }

  public long getLength() {
    return this.length;
  }

  public BinaryData setLength(long length) {
    this.length = length;
    setLengthIsSet(true);
    return this;
  }

  public void unsetLength() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LENGTH_ISSET_ID);
  }

  /** Returns true if field length is set (has been assigned a value) and false otherwise */
  public boolean isSetLength() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LENGTH_ISSET_ID);
  }

  public void setLengthIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LENGTH_ISSET_ID, value);
  }

  public java.lang.String getCheckalgorithm() {
    return this.checkalgorithm;
  }

  public BinaryData setCheckalgorithm(java.lang.String checkalgorithm) {
    this.checkalgorithm = checkalgorithm;
    return this;
  }

  public void unsetCheckalgorithm() {
    this.checkalgorithm = null;
  }

  /** Returns true if field checkalgorithm is set (has been assigned a value) and false otherwise */
  public boolean isSetCheckalgorithm() {
    return this.checkalgorithm != null;
  }

  public void setCheckalgorithmIsSet(boolean value) {
    if (!value) {
      this.checkalgorithm = null;
    }
  }

  public byte[] getCheckcodes() {
    setCheckcodes(org.apache.thrift.TBaseHelper.rightSize(checkcodes));
    return checkcodes == null ? null : checkcodes.array();
  }

  public java.nio.ByteBuffer bufferForCheckcodes() {
    return org.apache.thrift.TBaseHelper.copyBinary(checkcodes);
  }

  public BinaryData setCheckcodes(byte[] checkcodes) {
    this.checkcodes = checkcodes == null ? (java.nio.ByteBuffer)null : java.nio.ByteBuffer.wrap(checkcodes.clone());
    return this;
  }

  public BinaryData setCheckcodes(java.nio.ByteBuffer checkcodes) {
    this.checkcodes = org.apache.thrift.TBaseHelper.copyBinary(checkcodes);
    return this;
  }

  public void unsetCheckcodes() {
    this.checkcodes = null;
  }

  /** Returns true if field checkcodes is set (has been assigned a value) and false otherwise */
  public boolean isSetCheckcodes() {
    return this.checkcodes != null;
  }

  public void setCheckcodesIsSet(boolean value) {
    if (!value) {
      this.checkcodes = null;
    }
  }

  public byte[] getData() {
    setData(org.apache.thrift.TBaseHelper.rightSize(data));
    return data == null ? null : data.array();
  }

  public java.nio.ByteBuffer bufferForData() {
    return org.apache.thrift.TBaseHelper.copyBinary(data);
  }

  public BinaryData setData(byte[] data) {
    this.data = data == null ? (java.nio.ByteBuffer)null : java.nio.ByteBuffer.wrap(data.clone());
    return this;
  }

  public BinaryData setData(java.nio.ByteBuffer data) {
    this.data = org.apache.thrift.TBaseHelper.copyBinary(data);
    return this;
  }

  public void unsetData() {
    this.data = null;
  }

  /** Returns true if field data is set (has been assigned a value) and false otherwise */
  public boolean isSetData() {
    return this.data != null;
  }

  public void setDataIsSet(boolean value) {
    if (!value) {
      this.data = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case LENGTH:
      if (value == null) {
        unsetLength();
      } else {
        setLength((java.lang.Long)value);
      }
      break;

    case CHECKALGORITHM:
      if (value == null) {
        unsetCheckalgorithm();
      } else {
        setCheckalgorithm((java.lang.String)value);
      }
      break;

    case CHECKCODES:
      if (value == null) {
        unsetCheckcodes();
      } else {
        if (value instanceof byte[]) {
          setCheckcodes((byte[])value);
        } else {
          setCheckcodes((java.nio.ByteBuffer)value);
        }
      }
      break;

    case DATA:
      if (value == null) {
        unsetData();
      } else {
        if (value instanceof byte[]) {
          setData((byte[])value);
        } else {
          setData((java.nio.ByteBuffer)value);
        }
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case LENGTH:
      return getLength();

    case CHECKALGORITHM:
      return getCheckalgorithm();

    case CHECKCODES:
      return getCheckcodes();

    case DATA:
      return getData();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case LENGTH:
      return isSetLength();
    case CHECKALGORITHM:
      return isSetCheckalgorithm();
    case CHECKCODES:
      return isSetCheckcodes();
    case DATA:
      return isSetData();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof BinaryData)
      return this.equals((BinaryData)that);
    return false;
  }

  public boolean equals(BinaryData that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_length = true && this.isSetLength();
    boolean that_present_length = true && that.isSetLength();
    if (this_present_length || that_present_length) {
      if (!(this_present_length && that_present_length))
        return false;
      if (this.length != that.length)
        return false;
    }

    boolean this_present_checkalgorithm = true && this.isSetCheckalgorithm();
    boolean that_present_checkalgorithm = true && that.isSetCheckalgorithm();
    if (this_present_checkalgorithm || that_present_checkalgorithm) {
      if (!(this_present_checkalgorithm && that_present_checkalgorithm))
        return false;
      if (!this.checkalgorithm.equals(that.checkalgorithm))
        return false;
    }

    boolean this_present_checkcodes = true && this.isSetCheckcodes();
    boolean that_present_checkcodes = true && that.isSetCheckcodes();
    if (this_present_checkcodes || that_present_checkcodes) {
      if (!(this_present_checkcodes && that_present_checkcodes))
        return false;
      if (!this.checkcodes.equals(that.checkcodes))
        return false;
    }

    boolean this_present_data = true && this.isSetData();
    boolean that_present_data = true && that.isSetData();
    if (this_present_data || that_present_data) {
      if (!(this_present_data && that_present_data))
        return false;
      if (!this.data.equals(that.data))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetLength()) ? 131071 : 524287);
    if (isSetLength())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(length);

    hashCode = hashCode * 8191 + ((isSetCheckalgorithm()) ? 131071 : 524287);
    if (isSetCheckalgorithm())
      hashCode = hashCode * 8191 + checkalgorithm.hashCode();

    hashCode = hashCode * 8191 + ((isSetCheckcodes()) ? 131071 : 524287);
    if (isSetCheckcodes())
      hashCode = hashCode * 8191 + checkcodes.hashCode();

    hashCode = hashCode * 8191 + ((isSetData()) ? 131071 : 524287);
    if (isSetData())
      hashCode = hashCode * 8191 + data.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(BinaryData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetLength()).compareTo(other.isSetLength());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLength()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.length, other.length);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCheckalgorithm()).compareTo(other.isSetCheckalgorithm());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCheckalgorithm()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.checkalgorithm, other.checkalgorithm);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCheckcodes()).compareTo(other.isSetCheckcodes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCheckcodes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.checkcodes, other.checkcodes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetData()).compareTo(other.isSetData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.data, other.data);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("BinaryData(");
    boolean first = true;

    if (isSetLength()) {
      sb.append("length:");
      sb.append(this.length);
      first = false;
    }
    if (isSetCheckalgorithm()) {
      if (!first) sb.append(", ");
      sb.append("checkalgorithm:");
      if (this.checkalgorithm == null) {
        sb.append("null");
      } else {
        sb.append(this.checkalgorithm);
      }
      first = false;
    }
    if (isSetCheckcodes()) {
      if (!first) sb.append(", ");
      sb.append("checkcodes:");
      if (this.checkcodes == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.checkcodes, sb);
      }
      first = false;
    }
    if (isSetData()) {
      if (!first) sb.append(", ");
      sb.append("data:");
      if (this.data == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.data, sb);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BinaryDataStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BinaryDataStandardScheme getScheme() {
      return new BinaryDataStandardScheme();
    }
  }

  private static class BinaryDataStandardScheme extends org.apache.thrift.scheme.StandardScheme<BinaryData> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BinaryData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LENGTH
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.length = iprot.readI64();
              struct.setLengthIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CHECKALGORITHM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.checkalgorithm = iprot.readString();
              struct.setCheckalgorithmIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CHECKCODES
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.checkcodes = iprot.readBinary();
              struct.setCheckcodesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.data = iprot.readBinary();
              struct.setDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BinaryData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetLength()) {
        oprot.writeFieldBegin(LENGTH_FIELD_DESC);
        oprot.writeI64(struct.length);
        oprot.writeFieldEnd();
      }
      if (struct.checkalgorithm != null) {
        if (struct.isSetCheckalgorithm()) {
          oprot.writeFieldBegin(CHECKALGORITHM_FIELD_DESC);
          oprot.writeString(struct.checkalgorithm);
          oprot.writeFieldEnd();
        }
      }
      if (struct.checkcodes != null) {
        if (struct.isSetCheckcodes()) {
          oprot.writeFieldBegin(CHECKCODES_FIELD_DESC);
          oprot.writeBinary(struct.checkcodes);
          oprot.writeFieldEnd();
        }
      }
      if (struct.data != null) {
        if (struct.isSetData()) {
          oprot.writeFieldBegin(DATA_FIELD_DESC);
          oprot.writeBinary(struct.data);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BinaryDataTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BinaryDataTupleScheme getScheme() {
      return new BinaryDataTupleScheme();
    }
  }

  private static class BinaryDataTupleScheme extends org.apache.thrift.scheme.TupleScheme<BinaryData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BinaryData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetLength()) {
        optionals.set(0);
      }
      if (struct.isSetCheckalgorithm()) {
        optionals.set(1);
      }
      if (struct.isSetCheckcodes()) {
        optionals.set(2);
      }
      if (struct.isSetData()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetLength()) {
        oprot.writeI64(struct.length);
      }
      if (struct.isSetCheckalgorithm()) {
        oprot.writeString(struct.checkalgorithm);
      }
      if (struct.isSetCheckcodes()) {
        oprot.writeBinary(struct.checkcodes);
      }
      if (struct.isSetData()) {
        oprot.writeBinary(struct.data);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BinaryData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.length = iprot.readI64();
        struct.setLengthIsSet(true);
      }
      if (incoming.get(1)) {
        struct.checkalgorithm = iprot.readString();
        struct.setCheckalgorithmIsSet(true);
      }
      if (incoming.get(2)) {
        struct.checkcodes = iprot.readBinary();
        struct.setCheckcodesIsSet(true);
      }
      if (incoming.get(3)) {
        struct.data = iprot.readBinary();
        struct.setDataIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

